// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bidugndxaqtzcfouyvok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpZHVnbmR4YXF0emNmb3V5dm9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgyOTAzOTMsImV4cCI6MjA5Mzg2NjM5M30.bSqhg2bc_PMU7hKq7yNVUgrRf5NLbaBrW8zJ71TpsFU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== "undefined" ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});